/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import codigo.*;
import objetos.Delincuentes;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class pnlDelincuentes extends javax.swing.JPanel {

    ConsultasDB consultas = new ConsultasDB();
    Cargas cargas = new Cargas();
    
    public pnlDelincuentes() {
        initComponents();
        mostrarDatosJTable();
        mostrarDatosCombo();
    }
    
    public void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtAlias.setText("");
        txtPaisOrigen.setText("");
        txtRecompensa.setText("");
        txtCodTipoDelincuente.setText("");
        txtCodOrganizacion.setText("");
        txtCantidadDelitos.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
    }
    
    public void mostrarDatosJTable() {
        DefaultTableModel model = (DefaultTableModel) tbDatos.getModel();
        model.setRowCount(0);
        Delincuentes.listaDelincuentes = new ArrayList<>();
        ArrayList<Delincuentes> listaDelincuentes = cargas.cargarDelincuentes();
        Object[] arreglo = new Object[10];
        for (int i = 0; i < listaDelincuentes.size(); i++) {
            arreglo[0] = listaDelincuentes.get(i).getCodigo();
            arreglo[1] = listaDelincuentes.get(i).getNombre();
            arreglo[2] = listaDelincuentes.get(i).getFecha_nacimiento();
            arreglo[3] = listaDelincuentes.get(i).getPais_origen();
            arreglo[4] = listaDelincuentes.get(i).getRecompensa();
            arreglo[5] = listaDelincuentes.get(i).getAlias();
            arreglo[6] = listaDelincuentes.get(i).getTipo_delincuente();
            arreglo[7] = listaDelincuentes.get(i).getOrganizacion();
            arreglo[8] = listaDelincuentes.get(i).getFecha_primer_delito();
            arreglo[9] = listaDelincuentes.get(i).getCantidad_delitos();
            model.addRow(arreglo);
        }
    }
    
    public void mostrarDatosCombo() {
        cmbDelincuentes.setModel(cargas.cargarCodigosDelincuentes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCedula1 = new javax.swing.JLabel();
        lbBuscarEst = new javax.swing.JLabel();
        cmbDelincuentes = new javax.swing.JComboBox<>();
        txtRecompensa = new javax.swing.JTextField();
        txtPaisOrigen = new javax.swing.JTextField();
        lbCedula3 = new javax.swing.JLabel();
        lbCedula4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbCedula5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lbCedula = new javax.swing.JLabel();
        txtCantidadDelitos = new javax.swing.JTextField();
        txtCodTipoDelincuente = new javax.swing.JTextField();
        txtCodOrganizacion = new javax.swing.JTextField();
        txtAlias = new javax.swing.JTextField();
        lbCedula6 = new javax.swing.JLabel();
        lbCedula2 = new javax.swing.JLabel();
        lbCedula7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lbCedula8 = new javax.swing.JLabel();
        lbCedula9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));

        lbCedula1.setText("Nombre: ");

        lbBuscarEst.setText("Buscar Delincuentes:");

        cmbDelincuentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDelincuentesItemStateChanged(evt);
            }
        });

        txtRecompensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecompensaActionPerformed(evt);
            }
        });

        lbCedula3.setText("País Origen:");

        lbCedula4.setText("Recompensa:");

        lbCedula5.setText("Fecha nacimiento: ");

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Fecha Nacimiento", "País Origen", "Recompensa", "Alias", "Tipo Delincuente", "Organización", "Fecha Primer Delito", "Cantidad Delitos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        btnEliminar.setText("Borrar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(78, 32));
        btnEliminar.setMinimumSize(new java.awt.Dimension(78, 32));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Editar");
        btnModificar.setMaximumSize(new java.awt.Dimension(78, 32));
        btnModificar.setMinimumSize(new java.awt.Dimension(78, 32));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.setMaximumSize(new java.awt.Dimension(78, 32));
        btnInsertar.setMinimumSize(new java.awt.Dimension(78, 32));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        lbCedula.setText("Código:");

        txtCantidadDelitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDelitosActionPerformed(evt);
            }
        });

        lbCedula6.setText("Cod. Organizacion:");

        lbCedula2.setText("Alias:");

        lbCedula7.setText("Cantidad de delitos:");

        lbCedula8.setText("Fecha primer delito: ");

        lbCedula9.setText("Cod. Tipo de delincuente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(lbBuscarEst)
                .addGap(18, 18, 18)
                .addComponent(cmbDelincuentes, 0, 212, Short.MAX_VALUE)
                .addGap(395, 395, 395))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCedula4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRecompensa, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCedula3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCedula1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCedula)
                                .addGap(52, 52, 52)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCedula5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbCedula7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantidadDelitos, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCedula6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCodOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbCedula9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCodTipoDelincuente, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbCedula2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbCedula8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarEst)
                    .addComponent(cmbDelincuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCedula2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula3)
                            .addComponent(txtPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula4)
                            .addComponent(txtRecompensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCedula5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula9)
                            .addComponent(txtCodTipoDelincuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula6)
                            .addComponent(txtCodOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCedula7)
                            .addComponent(txtCantidadDelitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCedula8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDelincuentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDelincuentesItemStateChanged
        Integer codigo = (Integer) cmbDelincuentes.getSelectedItem();
        Delincuentes delincuentes = cargas.cargarUnDelincuentes(codigo);
        txtCodigo.setText(delincuentes.getCodigo().toString());
        txtNombre.setText(delincuentes.getNombre());
        jDateChooser1.setDate(delincuentes.getFecha_nacimiento());
        txtPaisOrigen.setText(delincuentes.getPais_origen());
        txtRecompensa.setText(delincuentes.getRecompensa().toString());
        txtAlias.setText(delincuentes.getAlias());
        txtCodTipoDelincuente.setText(delincuentes.getTipo_delincuente().toString());
        txtCodOrganizacion.setText(delincuentes.getOrganizacion().toString());
        jDateChooser2.setDate(delincuentes.getFecha_primer_delito());
        txtCantidadDelitos.setText(delincuentes.getCantidad_delitos().toString());
    }//GEN-LAST:event_cmbDelincuentesItemStateChanged

    private void txtRecompensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecompensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecompensaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Integer codigo = (Integer) cmbDelincuentes.getSelectedItem();
        consultas.ejecutarSQL("DELETE FROM delincuentes WHERE codigo = '" + codigo + "'");
        limpiarCampos();
        mostrarDatosJTable();
        mostrarDatosCombo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int recompensa = 0, organizacion = 0, cantidadDelitos = 0;
        int codigo = Integer.parseInt(txtCodigo.getText());
        String nombre = txtNombre.getText();
        Date fechaNacimiento = jDateChooser1.getDate();
        String paisOrigen = txtPaisOrigen.getText();
        if (txtRecompensa.getText().equals("")) {
            recompensa = 0;
        } else {
            recompensa = Integer.parseInt(txtRecompensa.getText());
        }
        String alias = txtAlias.getText();
        int tipoDelincuente = Integer.parseInt(txtCodTipoDelincuente.getText());
        if (txtCodOrganizacion.getText().equals("")) {
            organizacion = 0;
        } else {
            organizacion = Integer.parseInt(txtCodOrganizacion.getText());
        }
        Date fechaPrimerDelito = jDateChooser2.getDate();
        if (txtCantidadDelitos.getText().equals("")) {
            cantidadDelitos = 0;
        } else {
            cantidadDelitos = Integer.parseInt(txtCantidadDelitos.getText());
        }
        consultas.ejecutarSQL("UPDATE delincuentes SET nombre = '" + nombre + "', fecha_nacimiento = '" + fechaNacimiento + "', pais_origen = '" + paisOrigen + "', recompensa = " + recompensa + ", alias = '" + alias + "', tipo_delincuente = " + tipoDelincuente + ", organizacion = " + organizacion + ", fecha_primer_delito = '" + fechaPrimerDelito + "', cantidad_delitos = " + cantidadDelitos + " where codigo = "+codigo+"");
        limpiarCampos();
        mostrarDatosJTable();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        int recompensa = 0, organizacion = 0, cantidadDelitos = 0;
        int codigo = Integer.parseInt(txtCodigo.getText());
        String nombre = txtNombre.getText();
        Date fechaNacimiento = jDateChooser1.getDate();
        String paisOrigen = txtPaisOrigen.getText();
        if (txtRecompensa.getText().equals("")) {
            recompensa = 0;
        } else {
            recompensa = Integer.parseInt(txtRecompensa.getText());
        }
        String alias = txtAlias.getText();
        int tipoDelincuente = Integer.parseInt(txtCodTipoDelincuente.getText());
        if (txtCodOrganizacion.getText().equals("")) {
            organizacion = 0;
        } else {
            organizacion = Integer.parseInt(txtCodOrganizacion.getText());
        }
        Date fechaPrimerDelito = jDateChooser2.getDate();
        if (txtCantidadDelitos.getText().equals("")) {
            cantidadDelitos = 0;
        } else {
            cantidadDelitos = Integer.parseInt(txtCantidadDelitos.getText());
        }
        consultas.ejecutarSQL("INSERT INTO \"delincuentes\"(\"codigo\", \"nombre\", \"fecha_nacimiento\", \"pais_origen\", \"recompensa\", \"alias\", \"tipo_delincuente\", \"organizacion\", \"fecha_primer_delito\", \"cantidad_delitos\") VALUES ("+codigo+", '"+nombre+"', '"+fechaNacimiento+"', '"+paisOrigen+"', "+recompensa+", '"+alias+"', "+tipoDelincuente+", "+organizacion+", '"+fechaPrimerDelito+"', "+cantidadDelitos+");");
        limpiarCampos();
        mostrarDatosJTable();
        mostrarDatosCombo();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void txtCantidadDelitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDelitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadDelitosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbDelincuentes;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarEst;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbCedula1;
    private javax.swing.JLabel lbCedula2;
    private javax.swing.JLabel lbCedula3;
    private javax.swing.JLabel lbCedula4;
    private javax.swing.JLabel lbCedula5;
    private javax.swing.JLabel lbCedula6;
    private javax.swing.JLabel lbCedula7;
    private javax.swing.JLabel lbCedula8;
    private javax.swing.JLabel lbCedula9;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtCantidadDelitos;
    private javax.swing.JTextField txtCodOrganizacion;
    private javax.swing.JTextField txtCodTipoDelincuente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtRecompensa;
    // End of variables declaration//GEN-END:variables
}
