/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import codigo.Cargas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import objetos.Reporte;

/**
 *
 * @author gara8
 */
public class pnlDelincuentesAsignados extends javax.swing.JPanel {

    Cargas cargas = new Cargas();
    
    public pnlDelincuentesAsignados() {
        initComponents();
        mostrarDatosCombo();
    }
    
    public void mostrarDatosCombo() {
        cmbReporte.setModel(cargas.cargarCodigosAgentes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBuscarEst = new javax.swing.JLabel();
        cmbReporte = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        lbBuscarEst.setText("Generar reporte de:");

        cmbReporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbReporteItemStateChanged(evt);
            }
        });

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Agente", "Nombre del delincuente", "Alias delincuente", "Tipo de delincuente", "Nombre Organización"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(344, 344, 344)
                    .addComponent(lbBuscarEst)
                    .addGap(18, 18, 18)
                    .addComponent(cmbReporte, 0, 220, Short.MAX_VALUE)
                    .addGap(417, 417, 417))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(226, 226, 226)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbBuscarEst)
                        .addComponent(cmbReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(318, 318, 318)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbReporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbReporteItemStateChanged
        Integer codigo = (Integer) cmbReporte.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tbDatos.getModel();
        model.setRowCount(0);
        Reporte.listaReporte = new ArrayList<>();
        ArrayList<Reporte> listaReporte = cargas.cargarReporte(codigo);
        Object[] arreglo = new Object[5];
        for (int i = 0; i < listaReporte.size(); i++) {
            arreglo[0] = listaReporte.get(i).getNombreAgente();
            arreglo[1] = listaReporte.get(i).getNombreDelincuente();
            arreglo[2] = listaReporte.get(i).getAliasDelincuente();
            arreglo[3] = listaReporte.get(i).getNombreTipoDelincuente();
            arreglo[4] = listaReporte.get(i).getNombreOrganizacion();
            model.addRow(arreglo);
        }
    }//GEN-LAST:event_cmbReporteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscarEst;
    private javax.swing.JTable tbDatos;
    // End of variables declaration//GEN-END:variables
}
